[package]
name = "mqttest"
version = "0.1.0"
authors = ["Vincent de Phily <vincent.dephily@mobile-devices.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
futures = "0.1.28"
log = "0.4.7"
mqttrs = "0.2.0"
serde =  { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
time = "0.1.42"
tokio = "0.1.22"

#[[bin]]
#required-features = ["cli"]
structopt = "0.3.1"
env_logger = "0.7.0"
rand = "0.7.2"

