# See https://github.com/rust-lang-nursery/rustfmt for installation and setup.
# This config file uses unstable options, so a nightly version of rustfmt is needed.
# Might want to change a setting here when/if https://github.com/rust-lang-nursery/rustfmt/issues/2904 is resolved.
# Edition is needed to fix editor support, see https://github.com/rust-lang/rustfmt/issues/3104
indent_style = "Visual"
imports_indent = "Visual"
merge_imports = true
use_small_heuristics = "Max"
blank_lines_upper_bound = 2
match_block_trailing_comma = true
edition = "2018"
